default: &default
    adapter: cockroachdb
    host: localhost
    port: 5432
    username: skeletonkey
    password: ''
    database: skeletonkey

development:
    <<: *default

test:
    <<: *default
